### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/turbine#8]
Some stuff to do:

- [ ] Add link to gitter chat room
- [ ] Add camera
- [ ] Add a new entity
- [ ] Convert from meta data of entity format
- [ ] Write to entity file
- [ ] Create entities folder if it does not exists
- [ ] Get files in entities folder
- [ ] For each file in entities folder, load entity
- [ ] Add event for change in entity file
- [ ] Basic rendering with a single light source
